version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '03:00'
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: '03:00'
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.boot:*
      - dependency-name: org.apache.maven.plugins:maven-gpg-plugin
        versions:
          - ">= 3.0.1"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '04:00'
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2
