name: Pre-Release Publish

on:
  push:
    paths:
      - response-handler-*
    branch:
      - main
    tags-ignore:
      - v*
  workflow_dispatch:
  pull_request:
    types: [open]

jobs:

  pre-deploy-to-github:
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: "response-handler-starter"
      is_release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}