name: Publish Packages
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Deploy to GitHub
        run: mvn deploy -f release_pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}