name: Release Packages

on:
  push:
    paths:
      - response-handler-*
    branch:
      - main
    tags:
      - v*
  workflow_dispatch:
  pull_request:
    types: [open]

# 逻辑
# 1）普通的预发布 (pre-deploy-to-github) 将会先发布到 GitHub Repo, 然后执行 validated
# 2）如果这是 tag, validated 成功之后还会执行 deploy-to-github 和 deploy-to-ossrh

jobs:

  pre-deploy-to-github:
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      is_release: false
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

  validated:
    needs: [pre-deploy-to-github]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Load Maven Repository From Cache
        id: maven-local-repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-local-repository

      - name: Start validation
        run: cd spring-boot-demo; mvn test

  deploy-to-github:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [validated]
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: "response-handler-core"
      is_release: true
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

  deploy-to-ossrh:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ validated ]
    uses: ./.github/workflows/deploy-to-ossrh.yml
    secrets:
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}