name: Release Packages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  validated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Load Maven Repository From Cache
        id: maven-local-repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-local-repository

      - name: Start validation
        run: cd spring-boot-demo; mvn test

  deploy-to-github:
    needs: [validated]
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: "response-handler-plus/response-handler-starter"
      is_release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

  deploy-to-ossrh:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ validated ]
    uses: ./.github/workflows/deploy-to-ossrh.yml
    secrets:
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}