name: Release Packages

on:
  workflow_dispatch:
    inputs:
      module:
        default: "response-handler-core"
        description: "Specify the publishing module"
        required: true
        type: string
      is_release:
        default: false
        required: true
        type: boolean

jobs:
  github-repository:
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: ${{ inputs.module }}
      is_release: ${{ inputs.is_release }}
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

  deploy-to-ossrh:
    if: ${{ inputs.is_release }}
    uses: ./.github/workflows/deploy-to-ossrh.yml
