name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      module:
        default: "response-handler-core"
        description: "Specify the publishing module"
        required: true
        type: string

jobs:
  github-package:
    uses: ./.github/workflows/github-package.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: ${{ inputs.module }}
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

#  deploy-package:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#
#      - name: Deploy to GitHub Package
#        run: mvn clean deploy -am -pl ${{ inputs.module }} -DCI_RELEASE_URL=${{ env.CI_GITHUB_URL }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CI_GITHUB_URL: "https://maven.pkg.github.com/UNICKCHENG/Response-Handler"