name: Release Packages

on:
  push:
    paths:
      - response-handler-*
      - pom.xml
  workflow_dispatch:

jobs:
  github-repository:
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      is_release: false
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

  github-packages:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy-to-github.yml
    with:
      repository: "UNICKCHENG/maven-packages"
      module: "response-handler-core"
      is_release: true
    secrets:
      access-token: ${{ secrets.ACTION_PAT }}

